In [1]:
import numpy as np
n1 = np.array([10,20,30])
n1

array([10, 20, 30])

In [2]:
type(n1)

numpy.ndarray

In [4]:
n2 = np.array([[10,20,30],[50,60,70]])
n2

array([[10, 20, 30],
       [50, 60, 70]])

In [5]:
type(n2)

numpy.ndarray

In [4]:
import numpy as np
n3 = np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
import numpy as np
x=np.ones(3)
x

array([1., 1., 1.])

In [5]:
n4 = np.zeros((8,8))
n4

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
import numpy as np
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
import numpy as np
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [3]:
import numpy as np
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
n5=np.full((2,2),10)
n5

array([[10, 10],
       [10, 10]])

In [8]:
n6=np.arange(10,20)
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
n7=np.arange(10,60,5)
n7

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [10]:
n8=np.arange(1,111,11)
n8

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [8]:
np.linspace(1,20) #evenly spaced numbers between 11 and 20

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [10]:
#uniform distribution
np.random.rand(3)

array([0.27200633, 0.27961407, 0.58681082])

In [12]:
#standard normal distribution
np.random.randn(3)

array([-0.16006346, -1.58918083,  1.90723892])

In [13]:
np.random.randn(3,2)

array([[ 0.8456702 ,  2.64441579],
       [-2.09862981, -0.53838539],
       [ 0.42437771,  0.06127806]])

In [15]:
#random int
np.random.randint(1,100)

62

In [18]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [2]:
import numpy as np
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
arr[0:5]=109

In [5]:
arr

array([109, 109, 109, 109, 109,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [7]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [8]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
a[[2,1,0]]

array([[11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [13]:
a[:,[1,2]]

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
a[[1],[2]]

array([8])

In [3]:
import numpy as np
n10=np.array([[10,2,3],[3,4,5],[7,8,9],[9,8,7]])
n10.shape

(4, 3)

In [14]:
n10.shape=(3,4)

In [15]:
n10.shape

(3, 4)

In [21]:
c=np.arange(25)

In [22]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
d=np.arange(11,36)
d

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [25]:
d-c

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11])

In [26]:
d+c

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49, 51, 53, 55, 57, 59])

In [27]:
d*5-c*6

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31])

In [29]:
1/(d-c)

array([0.09090909, 0.09090909, 0.09090909, 0.09090909, 0.09090909,
       0.09090909, 0.09090909, 0.09090909, 0.09090909, 0.09090909,
       0.09090909, 0.09090909, 0.09090909, 0.09090909, 0.09090909,
       0.09090909, 0.09090909, 0.09090909, 0.09090909, 0.09090909,
       0.09090909, 0.09090909, 0.09090909, 0.09090909, 0.09090909])

In [31]:
np.sqrt(d)

array([3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
       5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978])

In [32]:
np.square(d)

array([ 121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225], dtype=int32)

In [33]:
np.exp(d) #exponential

array([5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
       3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
       1.78482301e+08, 4.85165195e+08, 1.31881573e+09, 3.58491285e+09,
       9.74480345e+09, 2.64891221e+10, 7.20048993e+10, 1.95729609e+11,
       5.32048241e+11, 1.44625706e+12, 3.93133430e+12, 1.06864746e+13,
       2.90488497e+13, 7.89629602e+13, 2.14643580e+14, 5.83461743e+14,
       1.58601345e+15])

In [34]:
np.max(c)

24

In [35]:
np.min(d)

11

In [36]:
np.cos(c)  #trignometric functions

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462,
        0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901])

In [38]:
c.sum(axis=0)

300

In [19]:
np.hstack((n1,n2))

array([[11,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 12, 13, 15]])

In [20]:
np.vstack((n1,n2))

array([[11,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [12, 13, 15]])

In [23]:
n1=np.array([[4,5,6]])
n2=np.array([[12,13,15,6,5]])
np.intersect1d(n1,n2)

array([5, 6])

In [24]:
np.setdiff1d(n1,n2)

array([4])

In [25]:
np.setdiff1d(n2,n1)

array([12, 13, 15])

In [5]:
import numpy as np
n1=np.array([[11,2,3],[4,5,6]])
n2=np.array([[7,8,9],[12,13,15]])
np.sum([n1,n2])

95

In [6]:
np.sum([n1,n2],axis=1)

array([[15,  7,  9],
       [19, 21, 24]])

In [7]:
import numpy as np
n1=np.array([[11,2,3],[4,5,6]])
n1=n1+2
n1

array([[13,  4,  5],
       [ 6,  7,  8]])

In [8]:
import numpy as np
n1=np.array([[11,2,3],[4,5,6]])
n1=n1-2
n1

array([[9, 0, 1],
       [2, 3, 4]])

In [11]:
import numpy as np
n1=np.array([[11,2,3],[4,5,6]])
n1/11
n1

array([[11,  2,  3],
       [ 4,  5,  6]])

In [13]:
import numpy as np
n1=np.array([[11,2,3],[4,5,6]])
np.mean(n1)


5.166666666666667

In [14]:
import numpy as np
n1=np.array([[11,2,3],[4,5,6]])
np.median(n1)

4.5

In [15]:
np.std(n1)

2.91070819942883

In [16]:
n1=np.array([10,20,30,40,50,60,70])
np.save('final_numpy_array',n1)
n2=np.load('final_numpy_array.npy')
n2

array([10, 20, 30, 40, 50, 60, 70])